### ISSUE TITLE
3d tiles need attribution

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#611]
Example implementation: https://glitch.com/edit/#!/maps-and-splats?path=index.html%3A89%3A0

Copy/paste of html and css below

The `street-geo` component 

``` html
    <div id="data-attribution">
      <div id="googleLogo">Google</div>
      <span id="copyright"></span>
    </div>
```

``` css
#data-attribution {
  position: absolute;
  bottom: 0;
  left: 0;
  padding: 10px;
  font-size: 14px;
  background-color: rgba(0, 0, 0, 0.3);
  color: white;
  z-index: 1;
}

#googleLogo {
  display: inline;        
  font-style: normal;
  font-weight: 500;
  font-size: 16px;
  line-height: 16px;
  padding: 16px;
  letter-spacing: 0.0575em; /* 0.69px */
  color: #FFFFFF;
}
#copyright {
  display:inline-block;
}
```
